Add reference check by alias and team [SUBS-501]
EMBL-EBI-SUBS/core-validator pull request #3
Opened 2017-06-22 15:23 UTC by fpenim

**WARN**
This is currently using the last working version of the `validator-common`:
[validator-common:48c266b9b0](https://github.com/EMBL-EBI-SUBS/validator-common/tree/48c266b9b0216cdba7f092cc91038760595a0e3a)

Updates:
- Added tests for all reference validators
- Added missing messaging configurations
- Added reference check by alias and team

2017-07-03 16:21 UTC, fpenim commented
**WARN**
This is now using the `validator-common-1.2.0-SNAPSHOT`

Please ignore failing codacy check.

2017-07-04 09:48 UTC, ke4 requested changes
Only small things :)

2017-07-04 09:48 UTC, ke4 commented on src/main/java/uk/ac/ebi/subs/validator/core/validators/SampleRefValidator.java
> +    String FAIL_MESSAGE = "Could not find reference target: %s .";
These constants are already defined in the AbstractReferenceValidator

2017-07-04 09:48 UTC, ke4 commented on src/test/java/uk/ac/ebi/subs/validator/core/validators/AssayRefValidatorTest.java
> +        System.out.println(singleValidationResult.getMessage());
Do we need the `System.out.println()` lines?

2017-07-04 10:03 UTC, fpenim commented on src/test/java/uk/ac/ebi/subs/validator/core/validators/AssayRefValidatorTest.java
> +        System.out.println(singleValidationResult.getMessage());
No we don't **need** it. But it's a visual help for the test results.

2017-07-04 10:14 UTC, ke4 approved these changes

2017-07-04 10:15 UTC, merged